server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0