spring:
  application:
    name: api-gateway

server:
  port: 8083


eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

zuul:
  routes:
    hellotest:
      path: /hello/**
      service-id: HelloClient